### ISSUE TITLE
not to be asked to choose in the terminal

### ISSUE THREAD

**Issue by daweedco** [Munter/yify-query#1]
Hi,

I'm trying to use your module to make a web app, but here is my problem, when i make a query like in the exemple and start my server, i'm forced to choose between a list a movie in the terminal.
I would like to be asked the same result in my web app but i don't know how to not make the module ask me in the terminal.

Thanks for your help

**Comment by Munter** [comment]
This module won't work outside of a terminal. It was never intended to. But it's not doing much more than just taking some input, do a bit of cleaning, query the API and present the options. You should be able to reimplement this in a browser compatible module pretty easily though

**Comment by daweedco** [comment]
Ok thanks for your fast answer Peter
